### PR TITLE
fix(DDI-1277) selected value not being changed programmatically

### PR DESCRIPTION
**Pull request by vanessatran-ddi**
### Description
The dropdown selected value is not being changed programmatically. 

Before with the below code: 
```
<h2>Reactive Binding
        <GoAButton onClick={() => setSelectedColor("red")} type="tertiary">
        Change to red
      </GoAButton>
      </h2>

      <div>Selected Color: {selectedColor}</div>
      <br/>
      <GoADropdown name="colors" placeholder="Select a color" onChange={(e) => setSelectedColor(e)} value={selectedColor}>
        <GoADropdownItem key="red" value="red" label="Red" />
        <GoADropdownItem key="green" value="green" label="Green" />
        <GoADropdownItem key="value" value="blue" label="Blue" />
      </GoADropdown>
```

**The value of the dropdown is not changed when we click the button.** 

### Stories/Tasks Link
- [DDIDS-1277](https://goa-dio.atlassian.net/browse/DDIDS-1277)

### Screenshots
Step 1: Pull this PR and build web components ```npm run build:web-components```
Step 2: Run Angular Demo App ```npm run run:angular-demo```
Step 3: Navigate to dropdown page: http://localhost:4200/dropdown

https://user-images.githubusercontent.com/120135417/226713340-3a667fd5-a5c7-48ed-9517-809a756e56b9.mov

Step 4: Stop Angular Demo App, run React app ```npm run run:react-demo```

https://user-images.githubusercontent.com/120135417/226713729-ed3440f3-bafb-4638-a8d0-d91cd9f689d2.mov

[DDIDS-1277]: https://goa-dio.atlassian.net/browse/DDIDS-1277?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by chrisolsen — DISMISSED** [review]

**Comment by chrisolsen** [comment]
@vanessatran-ddi You will need to add a space in your commit message (before `selected`)  to allow it to be parsed properly and added to the release docs

**Review by ArakTaiRoth — APPROVED** [review]

**Pull request merged**
