### PR TITLE
feat(#2175): add experimental form stepper for privacy portal team

### PR DESCRIPTION
**Pull request by vanessatran-ddi**
# Before (the change)
We don't have a privacy portal form stepper
# After (the change)
We add a privacy portal form stepper:
- goax-form-stepper
- goax-form-step
## Make sure that you've checked the boxes below before you submit the PR

- [x] I have read and followed the [setup steps](https://goa-dio.atlassian.net/wiki/spaces/DS/pages/3086385489/Contribution+-+web+content#%5BinlineExtension%5DCode-contributions)
- [ ] I have created necessary unit tests
- [x] I have tested the functionality in both React and Angular.

## Steps needed to test

This is how `form-stepper` on pp team can be done: 
https://github.com/vanessatran-ddi/latest-react-demo/blob/privacy-portal-components/src/react-wrapper-components/pp-form-stepper.tsx

image

image

### CODE REVIEW

**Review by syedszeeshan — APPROVED** [review]

**Comment by syedszeeshan** [comment]
There is a disaptch function in utils.ts which you might want to use. And I saw some code comments in the CSS section, not sure if you want to remove those or keep.

**Review by chrisolsen — APPROVED** [review]

**Pull request merged**
