### PR TITLE
fix(#1734): fix popover placement when displayed on the top of dropdown

### PR DESCRIPTION
**Pull request by chrisolsen**
Before (would not be visible)
image

After
image

Test Code
```
import { GoADropdown, GoADropdownItem } from "@abgov/react-components"

export function Bug1734Page() {
  function onChange() {
    // noop
  }
  
  return <>
    <div style={{
      height: "calc(100vh - 22rem)",
      width: "100%",
      display: "grid",
      gridTemplateColumns: "1fr 3fr 1fr",
      gridTemplateRows: "1fr 3fr 1fr",
      gridTemplateAreas: `
        "topleft . topright"
        ". center ."
        "bottomleft . bottomright"
      `,
    }}>
      <div style={{
        gridArea: "topleft"
      }}>
        <GoADropdown name="item" onChange={onChange}>
          <GoADropdownItem value="red" label="Red"></GoADropdownItem>
          <GoADropdownItem value="green" label="Green"></GoADropdownItem>
          <GoADropdownItem value="blue" label="Blue"></GoADropdownItem>
        </GoADropdown>
      </div> 
      <div style={{
        gridArea: "topright",
        display: "flex",
        justifyContent: "flex-end",
      }}>
        <GoADropdown name="item" onChange={onChange}>
          <GoADropdownItem value="red" label="RedRedRedRedRedRedRedRedRedRedRedRed"></GoADropdownItem>
          <GoADropdownItem value="green" label="Green"></GoADropdownItem>
          <GoADropdownItem value="blue" label="Blue"></GoADropdownItem>
        </GoADropdown>
      </div> 
      <div style={{
        gridArea: "center",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
      }}>
        <GoADropdown name="item" onChange={onChange}>
          <GoADropdownItem value="red" label="Red"></GoADropdownItem>
          <GoADropdownItem value="green" label="Green"></GoADropdownItem>
          <GoADropdownItem value="blue" label="Blue"></GoADropdownItem>
          <GoADropdownItem value="red" label="Red"></GoADropdownItem>
          <GoADropdownItem value="green" label="Green"></GoADropdownItem>
          <GoADropdownItem value="blue" label="Blue"></GoADropdownItem>
          <GoADropdownItem value="red" label="Red"></GoADropdownItem>
          <GoADropdownItem value="green" label="Green"></GoADropdownItem>
          <GoADropdownItem value="blue" label="Blue"></GoADropdownItem>
        </GoADropdown>
      </div> 
      <div style={{
        gridArea: "bottomleft",
        display: "flex",
        alignItems: "flex-end",
      }}>
        <GoADropdown name="item" onChange={onChange}>
          <GoADropdownItem value="red" label="Red"></GoADropdownItem>
          <GoADropdownItem value="green" label="Green"></GoADropdownItem>
          <GoADropdownItem value="blue" label="Blue"></GoADropdownItem>
          <GoADropdownItem value="red" label="Red"></GoADropdownItem>
          <GoADropdownItem value="green" label="Green"></GoADropdownItem>
          <GoADropdownItem value="blue" label="Blue"></GoADropdownItem>
          <GoADropdownItem value="red" label="Red"></GoADropdownItem>
          <GoADropdownItem value="green" label="Green"></GoADropdownItem>
          <GoADropdownItem value="blue" label="Blue"></GoADropdownItem>
        </GoADropdown>
      </div> 
      <div style={{
        gridArea: "bottomright",
        display: "flex",
        alignItems: "flex-end",
      }}>
        <GoADropdown name="item" onChange={onChange}>
          <GoADropdownItem value="red" label="Red"></GoADropdownItem>
          <GoADropdownItem value="green" label="Green"></GoADropdownItem>
          <GoADropdownItem value="blue" label="Blue"></GoADropdownItem>
          <GoADropdownItem value="red" label="Red"></GoADropdownItem>
          <GoADropdownItem value="green" label="Green"></GoADropdownItem>
          <GoADropdownItem value="blue" label="Blue"></GoADropdownItem>
          <GoADropdownItem value="red" label="Red"></GoADropdownItem>
          <GoADropdownItem value="green" label="Green"></GoADropdownItem>
          <GoADropdownItem value="blue" label="Blue"></GoADropdownItem>
        </GoADropdown>
      </div> 
    </div>
  </>
}
```

### CODE REVIEW

**Comment by ArakTaiRoth** [comment]
@lizhuomeng71 Can you also test issue #1746 while testing this PR?

**Comment by lizhuomeng71** [comment]
this issue is tested and verified, will continues to test on datepicker

**Comment by chrisolsen** [comment]
@lizhuomeng71 Are you able to move the PR into Review mode? If you don't see the image above we will have to bump up your permissions.
image

**Review by ArakTaiRoth — APPROVED** [review]

**Pull request merged**
