### PR TITLE
fix(#1763): filepicker's filetype filter when selecting files

### PR DESCRIPTION
**Pull request by chrisolsen**
Test Code

To test the issue change the `accept=".jpg, .pdf"` portion to test file types and [MIME types](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types/Common_types) (ex `image/*`, `image/bmp`, ...). *Note*: the `.` is required.

```
import { GoAFileUploadCard, GoAFileUploadInput, GoAFormItem } from "@abgov/react-components";
import { useState } from "react";

interface Uploader {
  upload: (url: string | ArrayBuffer) => void;
  abort: () => void;
}
interface Upload {
  name: string;
  file: File;
  uploader: Uploader;
}

class MockUploader implements Uploader {
  private processId?: any;

  public onprogress: (percent: number) => void = (_: number) => { };
  public onabort: () => void = () => { };
  public onfail: (err: string) => void = (_: string) => { };
  public oncomplete: () => void = () => { };

  upload(_url: string | ArrayBuffer) {
    let progress = 0;

    this.processId = setInterval(() => {
      progress += Math.random() * 10;
      this.onprogress(progress);
      if (progress >= 100) {
        this.oncomplete();
        clearInterval(this.processId);
      }
    }, 200);
  }

  abort() {
    // implement your logic to abort file upload
    console.log("implement logic here");
  }
}


export function BlankPage() {

  const [uploads, setUploads] = useState<Upload[]>([]);
  const [progressList, setProgressList] = useState<Record<string, number>>({});

  function deleteFile(file: Upload) {
    setUploads((uploadz) => {
      return uploadz.filter(u => u.name !== file.name);
    })
  }

  function uploadFile(file: File) {
    const reader = new FileReader();
    reader.onload = (e: ProgressEvent<FileReader>) => {
      if (!e.target) return;
      const url = e.target.result;
      const uploader = new MockUploader();

      setUploads(old => [...old, { name: file.name, file, uploader }]);

      uploader.onabort = () => console.log("Aborting upload");
      uploader.onfail = (err: string) => console.log("Upload failed: ", err);
      uploader.oncomplete = () => console.log("File upload complete");
      uploader.onprogress = (percent: number) => {
        setProgressList(old => ({ ...old, [file.name]: percent }));
      };

      if (url) {
        uploader.upload(url);
      }
    }
    reader.readAsDataURL(file);
  }

  return <>
    <GoAFormItem label="Upload a file">
      <GoAFileUploadInput onSelectFile={uploadFile} maxFileSize="100MB" accept=".jpg, .pdf" />
      {uploads.map(upload => (
        <GoAFileUploadCard
          key={upload.file.name}
          filename={upload.file.name}
          type={upload.file.type}
          size={upload.file.size}
          progress={progressList[upload.file.name]}
          onDelete={() => deleteFile(upload)}
          onCancel={() => deleteFile(upload)}
        />
      ))}
    </GoAFormItem>
  </>
}
```

### CODE REVIEW

**Comment by lizhuomeng71** [comment]
Hi @chrisolsen, could you please give me a example about what is been fixed? Thanks very much

**Comment by lizhuomeng71** [comment]
Issues is verified on Chrome, Firefox, and edge for react and angular, for mobile and desktop site
Screenshot 2024-04-11 143610
Screenshot 2024-04-11 144105
Screenshot 2024-04-11 144240

**Review by ArakTaiRoth — APPROVED** [review]

**Pull request merged**
