### PR TITLE
 feat (DDI-641): Close modal on esc key press

### PR DESCRIPTION
**Pull request by amar-ABgov**

### CODE REVIEW

**Comment by Radha-Alberta** [comment]
- Error is seen in console logs when modal is opened second time

https://user-images.githubusercontent.com/107069489/223515943-cb044f02-518d-4639-a287-36c7b313af15.mp4

**Review by ArakTaiRoth — APPROVED** [review]

**Review by vanessatran-ddi — APPROVED** [review]

**Pull request merged**
