### PR TITLE
fix(#1900): fix app header console error below 1024px

### PR DESCRIPTION
**Pull request by syedszeeshan**
# Before (the change)
Below 1024, the console error shows up (screenshot below)
image

# After (the change)
No more console errors.

## Make sure that you've checked the boxes below before you submit the PR

- [x] I have read and followed the [setup steps](https://goa-dio.atlassian.net/wiki/spaces/DS/pages/3086385489/Contribution+-+web+content#%5BinlineExtension%5DCode-contributions)
- [ ] I have created necessary unit tests
- [x] I have tested the functionality in both React and Angular.

### CODE REVIEW

**Comment by lizhuomeng71** [comment]
issue is verified for firefox and angular. the console error will show when there is no nav-items

**Review by ArakTaiRoth — APPROVED** [review]

**Pull request merged**
