### PR TITLE
fix: prevent all the semicolons from being replaced with a space

### PR DESCRIPTION
**Pull request by chrisolsen**
# Before (the change)

# After (the change)

## Make sure that you've checked the boxes below before you submit the PR

- [ x] I have read and followed the [setup steps](https://goa-dio.atlassian.net/wiki/spaces/DS/pages/3086385489/Contribution+-+web+content#%5BinlineExtension%5DCode-contributions)
- [ ] I have created necessary unit tests
- [x] I have tested the functionality in both React and Angular.

## Steps needed to test

```
<div>Some Text</div>
<goa-text as="h2" mt="xl" mb="xl">
   There should be padding above this text
</goa-text>
```

### CODE REVIEW

**Comment by lizhuomeng71** [comment]
verified on react and angular

**Review by ArakTaiRoth — APPROVED** [review]

**Pull request merged**
