### PR TITLE
fix(#1799): tooltip maintain mouse cursor style on hover

### PR DESCRIPTION
**Pull request by syedszeeshan**
# Before (the change)
cursor changes to a hand on hover

# After (the change)
cursor stays the same on hover

## Make sure that you've checked the boxes below before you submit the PR

- [x] I have read and followed the [setup steps](https://goa-dio.atlassian.net/wiki/spaces/DS/pages/3086385489/Contribution+-+web+content#%5BinlineExtension%5DCode-contributions)
- [x] I have created necessary unit tests
- [ ] I have tested the functionality in both React and Angular.

### CODE REVIEW

**Comment by syedszeeshan** [comment]
image

**Comment by lizhuomeng71** [comment]
issue is verified on react and angular

**Review by chrisolsen — APPROVED** [review]

**Pull request merged**
