### PR TITLE
1972 form item dynamic error

### PR DESCRIPTION
**Pull request by chrisolsen**
# Before (the change)

# After (the change)

## Make sure that you've checked the boxes below before you submit the PR

- [x] I have read and followed the [setup steps](https://goa-dio.atlassian.net/wiki/spaces/DS/pages/3086385489/Contribution+-+web+content#%5BinlineExtension%5DCode-contributions)
- [x] I have created necessary unit tests
- [x] I have tested the functionality in both React and Angular.

## Steps needed to test

Angular
```
    <goa-radio-group name="item" [error]="errorVariable" mb="xl">
      <goa-radio-item
        value="Test 1"
        label="Test 1"
      />
      <goa-radio-item
        value="Test 2"
        label="Test 2"
      />
      <goa-radio-item
        value="Test 3"
        label="Test 3"
      />
    </goa-radio-group>
    <br />
    <goa-button (_click)="setError()">Set Error</goa-button>
```

React
```
  const [error, setError] = React.useState<boolean>(false);

  return (
     <>
      <GoAButton onClick={() => setError(true)}>Show Error</GoAButton>
      <GoARadioGroup name="color2" value="orange" error={error} onChange={onChange}>
        <GoARadioItem name="color2" value="red"></GoARadioItem>
        <GoARadioItem name="color2" value="blue"></GoARadioItem>
        <GoARadioItem name="color2" value="orange"></GoARadioItem>
      </GoARadioGroup>
     </>
   )

```

### CODE REVIEW

**Comment by lizhuomeng71** [comment]
I have verified on react and angular, and also other component that has error properties

image

**Comment by lizhuomeng71** [comment]
issue is verified on react and angular, I will create an sperate task for create cypress for this ticket

**Review by syedszeeshan — APPROVED** [review]

**Pull request merged**
