### PR TITLE
bug/2018: fix active links are pushed down

### PR DESCRIPTION
**Pull request by vanessatran-ddi**
# Before (the change)
image

# After (the change)
image

## Make sure that you've checked the boxes below before you submit the PR

- [x] I have read and followed the [setup steps](https://goa-dio.atlassian.net/wiki/spaces/DS/pages/3086385489/Contribution+-+web+content#%5BinlineExtension%5DCode-contributions)
- [x] I have created necessary unit tests
- [x] I have tested the functionality in both React and Angular.

### CODE REVIEW

**Comment by lizhuomeng71** [comment]
when nav has  className="interactive", the top margin is gone

image

**Comment by lizhuomeng71** [comment]
issue is verified on react and angular. mobile and desktop

**Review by ArakTaiRoth — APPROVED** [review]

**Pull request merged**
