### PR TITLE
feat(#2053): allow slotted content in microsite header version

### PR DESCRIPTION
**Pull request by bdfranck**
This PR allows slotted content in the "version" section of the microsite header. It's based off the previous work in the https://github.com/GovAlta/ui-components/pull/1853.

## Before the change
The `version` property on the microsite header only accepts a string.
image

## After the change
The `version` property accepts slotted content...
image

...or a string.
image

The slotted `div` has the following layout to align with the [Figma design](https://www.figma.com/design/c7d7OviJ2Z04CrM66KLuiW/Enable-switching-between-library-versions-on-the-design-system-website?node-id=26-31830&t=hPQ9A3Y7Qpv7ucJJ-1):
- Is placed in a `flex` row
- Has a `space-m` gap
- Items are vertically aligned `center`

image

I also did a bit of tech debt. I replaced any stray `rem` values CSS with GOA space custom properties.

### Angular
```html
<goa-microsite-header type="alpha" version="UAT"></goa-microsite-header>
    
<goa-microsite-header type="alpha">
  <div slot="version">
     <a href="#" id="microsite-version-angular">Angular</a>
     <a href="#">v2.3.4</a>
  </div>
</goa-microsite-header>
``` 

### React
```html
<GoAMicrositeHeader type="alpha" version="UAT" />

<GoAMicrositeHeader type="alpha" version={<><a href="#">Angular</a><a href="#">v1.2.3</a></>} />
``` 

## Checklist
- [x] I have created necessary unit tests
- [x] I have tested the functionality in both React and Angular.

## Outstanding questions
- Do we have unit tests for slotted components? I couldn't see any for `formItem`. 🤔 
- I'm assuming that we almost always want the content of `version` in a flex row with a gap between items. Is this true? If not, I can remove the styling.

### CODE REVIEW

**Comment by bdfranck** [comment]
I've updated my PR with unit tests for a slotted version in both angular and react.

**Comment by bdfranck** [comment]
I tested on the latest browsers...

It works on the latest version of Edge. 👍 
image

It works on the latest version of Chrome. 👍 
image

It works on the latest version of Safari. 👍 
image

It works on the latest version of Firefox. 👍 
image

**Review by syedszeeshan — APPROVED** [review]

**Review by chrisolsen — APPROVED** [review]

**Pull request merged**
