### PR TITLE
fix(#1954): prevent dropdown firing _change event  when the value is reselected

### PR DESCRIPTION
**Pull request by chrisolsen**
# Before (the change)
https://jam.dev/c/9a8ae231-c3d9-4762-bff1-34ee4c03efe8

# After (the change)
https://jam.dev/c/8db31b77-a73a-4fe8-9c69-c0ede712b240

## Make sure that you've checked the boxes below before you submit the PR

- [x] I have read and followed the [setup steps](https://goa-dio.atlassian.net/wiki/spaces/DS/pages/3086385489/Contribution+-+web+content#%5BinlineExtension%5DCode-contributions)
- [x] I have created necessary unit tests
- [x] I have tested the functionality in both React and Angular.

## Steps needed to test

- [ ] For non-filterable dropdown validate that when selecting the same value repeatedly, that events are only fired the first time.
- [ ] For the filterable dropdown validate that the when clearing the selection that events are fired with a blank value and that an event is fired when you delete the filter text and Tab away

### CODE REVIEW

**Comment by lizhuomeng71** [comment]
Issue is verified on angular and react, for autocompleted dropdown and filter

**Review by ArakTaiRoth — APPROVED** [review]

**Pull request merged**
