### PR TITLE
fix(#2044): add disabled prop to datepicker

### PR DESCRIPTION
**Pull request by vanessatran-ddi**
# Before (the change)
Datepicker has no property `disabled`
# After (the change)
Datepicker has the new property `disabled`

## Make sure that you've checked the boxes below before you submit the PR

- [x] I have read and followed the [setup steps](https://goa-dio.atlassian.net/wiki/spaces/DS/pages/3086385489/Contribution+-+web+content#%5BinlineExtension%5DCode-contributions)
- [x] I have created necessary unit tests
- [x] I have tested the functionality in both React and Angular.

### React:

https://github.com/user-attachments/assets/70bbffdb-f0a3-4cbd-a5bd-2da5dbdb6421

```
import { GoAButton, GoADatePicker, GoAFormItem } from "@abgov/react-components";
import { useState } from "react";

export function Datepicker() {
  const [value, setValue] = useState<Date>(new Date(2024, 3, 26));
  const [disabled, setDisabled] = useState<boolean>(false);

  function onChange(name: string, value: Date) {
    console.log("onChange is triggered ", name, value);
    setValue(value);
  }

  function toggleDisabled() {
    setDisabled(!disabled);
  }

  return (
    <>
      <GoAButton mb="xl" onClick={toggleDisabled}>
        Toggle Disabled State
      </GoAButton>
      <GoAFormItem label="Item">
        <GoADatePicker
          onChange={onChange}
          name="item"
          value={value}
          disabled={disabled}
        ></GoADatePicker>
      </GoAFormItem>
    </>
  );
}

```

### Angular:

https://github.com/user-attachments/assets/12e948d0-c6a1-43d7-8410-7231c8d551a6

```
<goa-button-group alignment="center" mb="xl">
  <goa-button (_click)="enableDatePicker()">Enable</goa-button>
  <goa-button (_click)="disableDatePicker()">Disable</goa-button>
</goa-button-group>

<h4>Angular form control</h4>
<goa-date-picker goaValue [formControl]="reactiveDate2FormCtrl"></goa-date-picker>

<h4>Event:</h4>
<goa-date-picker
  goaValue
  [formControl]="reactiveDate2FormCtrl"
  [attr.disabled]="disabled"
></goa-date-picker>
```

```
disabled = false;
reactiveDate2FormCtrl = new FormControl(new Date());
disableDatePicker() {
    this.reactiveDate2FormCtrl.disable();
    this.disabled = true;
  }

  enableDatePicker() {
    this.reactiveDate2FormCtrl.enable();
    this.disabled = false;
  }
```

### CODE REVIEW

**Comment by ArakTaiRoth** [comment]
I can't seem to disable the Date Picker in Angular using the provided code, nor any other combination of disabled and true

**Comment by lizhuomeng71** [comment]
This issue is verified for react and angular

**Review by syedszeeshan — APPROVED** [review]

**Review by chrisolsen — APPROVED** [review]

**Pull request merged**
