### PR TITLE
fix #1149 trailing icon position

### LINKED ISSUE #1149: Icon button position in input
**Issue**

When using `trailingIcon`, icon placement in input is to close to the right edge of the input

## Acceptance criteria

* Update input so that icon is 12px `--goa-spacing-s` from right side of input

image-20230515-213718

### PR DESCRIPTION
**Pull request by Radha-Alberta**

### CODE REVIEW

**Comment by ArakTaiRoth** [comment]
- [ ] Doesn't actually do anything if the icon is an icon button. Only adjusts the padding if the icon is just an icon. Examples below:
image
In React, if you use this code it works:
```typescript
<GoAInput
  name=""
  value=""
  onChange={noop}
  type="text"
  trailingIcon="finger-print"
>
```
But if you use this code, it doesn't:
```typescript
<GoAInput
  trailingIcon="finger-print"
  name=""
  value=""
  onChange={noop}
  type="text"
  onTrailingIconClick={noop}
/>
```

Also @twjeffery. should the `leadingIcon` also have this extra padding?
image

**Comment by twjeffery** [comment]
@ArakTaiRoth I don't know what the padding is exactly from your screenshots, but it looks correct. I've attached the specs from design for leading and trailing icons within an input.
image
image

**Review by ArakTaiRoth — APPROVED** [review]

**Review by chrisolsen — CHANGES_REQUESTED** [review]
You will need to squash your commits.

**Comment by chrisolsen** [comment]
The commit message will still need to follow the `fix:` convention to trigger npm releases

**Review by chrisolsen — APPROVED** [review]

**Pull request merged**
