### PR TITLE
fix(#2036): side menu group console error

### PR DESCRIPTION
**Pull request by syedszeeshan**
# Before (the change)

# After (the change)

## Make sure that you've checked the boxes below before you submit the PR

- [x] I have read and followed the [setup steps](https://goa-dio.atlassian.net/wiki/spaces/DS/pages/3086385489/Contribution+-+web+content#%5BinlineExtension%5DCode-contributions)
- [ ] I have created necessary unit tests
- [x] I have tested the functionality in both React and Angular.

## Steps needed to test

**Before the code change**
-Copy the code from the story#2036
-Browse to the side menu link
-And then go to any other link
-console error pops up, note the error

**Apply the code changes**
-Repeat the above steps
-should not genereate the previously noted console error

### CODE REVIEW

**Comment by syedszeeshan** [comment]
image

**Review by ArakTaiRoth — APPROVED** [review]

**Pull request merged**
