### PR TITLE
feat(#2035): BREAKING CHANGE - remove web-components from react library

### PR DESCRIPTION
**Pull request by vanessatran-ddi**
# Before (the change)

# After (the change)

React app will look like this if we don't import `@abgov/web-components`
image

After import it under `App.tsx`
image

## Make sure that you've checked the boxes below before you submit the PR

- [x] I have read and followed the [setup steps](https://goa-dio.atlassian.net/wiki/spaces/DS/pages/3086385489/Contribution+-+web+content#%5BinlineExtension%5DCode-contributions)
- [ ] I have created necessary unit tests
- [x] I have tested the functionality in both React and Angular.

### CODE REVIEW

**Review by ArakTaiRoth — APPROVED** [review]

**Review by syedszeeshan — APPROVED** [review]

**Comment by ArakTaiRoth** [comment]
@vanessatran-ddi You need to change your commit message to be the same as [this](https://www.conventionalcommits.org/en/v1.0.0/#commit-message-with-both--and-breaking-change-footer)

**Pull request merged**
