### PR TITLE
fix(#1716): Removed '.' from default file upload text

### PR DESCRIPTION
**Pull request by ArakTaiRoth**
# Before (the change)

Text in File Upload Card will say "Maximum file size is `x`."

# After (the change)

Text in File Upload Card will say "Maximum file size is 'x'"

Note the missing "." at the end.

## Make sure that you've checked the boxes below before you submit the PR

- [x] I have read and followed the [setup steps](https://goa-dio.atlassian.net/wiki/spaces/DS/pages/3086385489/Contribution+-+web+content#%5BinlineExtension%5DCode-contributions)
- [x] I have created necessary unit tests
- [x] I have tested the functionality in both React and Angular.

## Steps needed to test

Just use a File Upload Card

### CODE REVIEW

**Comment by lizhuomeng71** [comment]
image

**Comment by lizhuomeng71** [comment]
we should also remove the end period, when the variant="button", as show on the above photo

**Review by chrisolsen — APPROVED** [review]

**Comment by lizhuomeng71** [comment]
this issue is verified on react and angular

**Pull request merged**
