### PR TITLE
Fix dropdown tab scroll issue

### PR DESCRIPTION
**Pull request by chrisolsen**

### CODE REVIEW

**Review by ArakTaiRoth — APPROVED** [review]

**Comment by Radha-Alberta** [comment]
- [ ] the page is scrolling on arrow keys. but not going to other dropdown options

**Comment by chrisolsen** [comment]
> * [ ]  the page is scrolling on arrow keys. but not going to other dropdown options

That fix is in a different PR

**Review by vanessatran-ddi — APPROVED** [review]

**Review by Radha-Alberta — APPROVED** [review]

**Pull request merged**
