### PR TITLE
fix(#2103): button group leading Icon is out of alignment

### PR DESCRIPTION
**Pull request by syedszeeshan**
# Before (the change)

# After (the change)
-Test code examples below with and without button group

## Make sure that you've checked the boxes below before you submit the PR

- [x] I have read and followed the [setup steps](https://goa-dio.atlassian.net/wiki/spaces/DS/pages/3086385489/Contribution+-+web+content#%5BinlineExtension%5DCode-contributions)
- [ ] I have created necessary unit tests
- [x] I have tested the functionality in both React and Angular.

## Steps needed to test

**Angular Test Code**
```
<h2>Using Button Group</h2>
<goa-button-group>
  <goa-button type="primary" size="compact" (_click)="onClick()">
    Button
  </goa-button>
  <goa-button type="primary" size="compact" leadingicon="arrow-forward" (_click)="onClick()">
    Button
  </goa-button>
  <goa-button type="primary" size="compact" trailingicon="arrow-forward" (_click)="onClick()">
    Button
  </goa-button>
</goa-button-group>

<h2>Without button group (inside a div)</h2>
<div style="display: flex;">
  <goa-button type="primary" size="compact" (_click)="onClick()" mr="xs">
    Button
  </goa-button>
  <goa-button type="primary" size="compact" leadingicon="arrow-forward" (_click)="onClick()"  ml="xs" mr="xs">
    Button
  </goa-button>
  <goa-button type="primary" size="compact" trailingicon="arrow-forward" (_click)="onClick()" ml="xs">
    Button
  </goa-button>
</div>
```

```
import { Component } from "@angular/core";

@Component({
  selector: "abgov-button-group",
  templateUrl: "./button-group.component.html",
})
export class ButtonGroupComponent {

  onClick() {
    console.log("clicked");
  }
}
```

React Test Code

```
import * as React from "react";
import { GoAButtonGroup, GoAButton } from "@abgov/react-components";

export default function ButtonGroup() {
  function onClick() {
    console.log("clicked");
  }
return (
    <>
      <h2>Using Button Group</h2>
      <GoAButtonGroup alignment="start">
        <GoAButton type="primary" size="compact">
          Button
        </GoAButton>
        <GoAButton type="submit" size="compact" leadingIcon="arrow-forward">
          Button
        </GoAButton>
        <GoAButton type="submit" size="compact" trailingIcon="arrow-forward">
          Button
        </GoAButton>
      </GoAButtonGroup>

      <h2>Without button group (inside a div)</h2>
      <div style={{ display: "flex" }}>
        <GoAButton type="primary" size="compact" mr="xs">
          Button
        </GoAButton>
        <GoAButton
          type="submit"
          size="compact"
          leadingIcon="arrow-forward"
          ml="xs"
          mr="xs"
        >
          Button
        </GoAButton>
        <GoAButton type="submit" size="compact" trailingIcon="arrow-forward" ml="xs">
          Button
        </GoAButton>
      </div>
    </>
  );
}  
```

### CODE REVIEW

**Comment by lizhuomeng71** [comment]
Issue is verified and fixed

image

**Review by ArakTaiRoth — APPROVED** [review]

**Pull request merged**
