### PR TITLE
feat(#1454): add pencil outline icon

### PR DESCRIPTION
**Pull request by vanessatran-ddi**
# Before (the change)
Using the code: 
```
<goa-icon type="pencil"></goa-icon>
<goa-icon type="pencil" theme="filled"></goa-icon>
```
They are the same now. Expected they are different. When no `theme` is specified, the `outline` should be displayed. Pencil icon is missing `outline` variant. 

# After (the change)
image

## Make sure that you've checked the boxes below before you submit the PR

- [x] I have read and followed the [setup steps](https://goa-dio.atlassian.net/wiki/spaces/DS/pages/3086385489/Contribution+-+web+content#%5BinlineExtension%5DCode-contributions)
- [x] I have created necessary unit tests
- [x] I have tested the functionality in both React and Angular.

### CODE REVIEW

**Comment by lizhuomeng71** [comment]
FIlled Icon and outline icon is not at the same height. 

image

**Comment by lizhuomeng71** [comment]
issue is verified on react and angular

image

**Review by ArakTaiRoth — APPROVED** [review]

**Review by chrisolsen — APPROVED** [review]

**Pull request merged**
