### PR TITLE
fix(#1396): allow tables to autoscroll when a high column count exists

### PR DESCRIPTION
**Pull request by chrisolsen**

### CODE REVIEW

**Comment by chrisolsen** [comment]
Add the following to your App.svelte file to test it
```
<goa-table>
    <thead>
      <tr>
        <th>Col 1</th>
        <th>Col 2</th>
        <th>Col 3</th>
        <th>Col 4</th>
        <th>Col 5</th>
        <th>Col 6</th>
        <th>Col 7</th>
        <th>Col 8</th>
        <th>Col 9</th>
        <th>Col 10</th>
        <th>Col 11</th>
        <th>Col 12</th>
        <th>Col 13</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>
          <goa-block alignment="center" gap="xs">
            <goa-icon type="alarm"></goa-icon>Item 1
          </goa-block>
        </td>
        <td>Item 2</td>
        <td>Item 3</td>
        <td>Item 4</td>
        <td>Item 5</td>
        <td>Item 6</td>
        <td>Item 7</td>
        <td>Item 8</td>
        <td>Item 9</td>
        <td>Item 10</td>
        <td>Item 11</td>
        <td>Item 12</td>
        <td>Item 13</td>
      </tr>
      <tr>
        <td>
          <goa-block alignment="center" gap="xs">
            <goa-icon type="alarm"></goa-icon>Item 1
          </goa-block>
        </td>
        <td>Item 2</td>
        <td>Item 3</td>
        <td>Item 4</td>
        <td>Item 5</td>
        <td>Item 6</td>
        <td>Item 7</td>
        <td>Item 8</td>
        <td>Item 9</td>
        <td>Item 10</td>
        <td>Item 11</td>
        <td>Item 12</td>
        <td>Item 13</td>
      </tr>
    </tbody>
  </goa-table>
```

**Review by ArakTaiRoth — DISMISSED** [review]

**Review by Radha-Alberta — APPROVED** [review]

**Review by ArakTaiRoth — APPROVED** [review]

**Review by Radha-Alberta — APPROVED** [review]

**Pull request merged**
