### PR TITLE
Critical bug fixes

### PR DESCRIPTION
**Pull request by chrisolsen**
## App Header (Mobile)
Before
image

After
image

## Tabs (Mobile)
Before
image

After
image

### CODE REVIEW

**Comment by lizhuomeng71** [comment]
issue is verified and passed for firefox. chrome and edge, for react and angular and for desktop and mobile, 

however, I did notice something I am not sure with

for tab that have :focus-visible status, tab will have a highlighted borders, please see attached screen shot

step to reproduce
1, go to https://design.alberta.ca/components/tabs#tab-0
2. refresh the page

 
Screenshot 2024-03-25 160256

**Comment by lizhuomeng71** [comment]
> issue is tested on chrome, firefox, edge, for react and angular for desktop and mobile site, moved to ready for review

**Review by ArakTaiRoth — APPROVED** [review]

**Pull request merged**
