### PR TITLE
fix(#2032): change icon theme dynamically

### PR DESCRIPTION
**Pull request by vanessatran-ddi**
# Before (the change)
Cannot change the icon theme
# After (the change)
Can change it
https://jam.dev/c/6725a8af-6e2a-4f79-8a2d-239c33d6cdbe

## Make sure that you've checked the boxes below before you submit the PR

- [x] I have read and followed the [setup steps](https://goa-dio.atlassian.net/wiki/spaces/DS/pages/3086385489/Contribution+-+web+content#%5BinlineExtension%5DCode-contributions)
- [x] I have created necessary unit tests
- [x] I have tested the functionality in both React and Angular.

## Steps needed to test

```
<h2>Dynamic changing theme</h2>
<goa-button (_click)="changeTheme()">Change theme</goa-button>
<goa-icon type="accessibility" [theme]="iconTheme"></goa-icon>
{{ iconTheme }}
```

```
@Component({
  selector: "abgov-icon",
  templateUrl: "./icon.component.html"
})
export class IconComponent {
  iconTheme = "outline";
  constructor() {}

  changeTheme() {
    this.iconTheme = this.iconTheme === "filled" ? "outline" : "filled";
  }
}
```

### CODE REVIEW

**Comment by lizhuomeng71** [comment]
this issue is fixed, an sperate issue regard goa-icon-button is created, new issue can be found here

https://github.com/GovAlta/ui-components/issues/2037

https://jam.dev/c/4e5552d8-c340-4dc4-8bc2-f4f8e03d5351

**Review by chrisolsen — APPROVED** [review]

**Review by ArakTaiRoth — APPROVED** [review]

**Pull request merged**
