### PR TITLE
Fix 1732 and 1733

### PR DESCRIPTION
**Pull request by chrisolsen**

### CODE REVIEW

**Comment by lizhuomeng71** [comment]
Screenshot 2023-02-28 174409

when we have <goa-spacer hSpacing="fill"></goa-spacer>, the text on each end will wrap, please see screen shot

```
<h3>Fill</h3>
   <goa-block direction="row">
     <div  [ngStyle]="{'background-color': 'skyblue', 'padding': '1rem'}">
       Item 1 C D E
     </div>
     <goa-spacer hSpacing="fill"></goa-spacer>
     <div  [ngStyle]="{'background-color': 'skyblue', 'padding': '1rem'}">
       Item 1 C D E
     </div>
   </goa-block>
```

**Comment by lizhuomeng71** [comment]
Issue is verified on react / angular. on chrome and firefox, move to ready for review

**Review by ArakTaiRoth — APPROVED** [review]

**Comment by chrisolsen** [comment]
> Screenshot 2023-02-28 174409
> 
> when we have `<goa-spacer hSpacing="fill"></goa-spacer> `, the text on each end will wrap, please see screen shot
> 
> ```
> <h3>Fill</h3>
>    <goa-block direction="row">
>      <div  [ngStyle]="{'background-color': 'skyblue', 'padding': '1rem'}">
>        Item 1 C D E
>      </div>
>      <goa-spacer hSpacing="fill"></goa-spacer>
>      <div  [ngStyle]="{'background-color': 'skyblue', 'padding': '1rem'}">
>        Item 1 C D E
>      </div>
>    </goa-block>
> ```

Adding a `white-space: nowrap` style or setting a set width would be required on the user's side to do that.

**Pull request merged**
