### PR TITLE
fix(#1294): Accordion heading not responding correctly on smaller scr…

### PR DESCRIPTION
**Pull request by vanessatran-ddi**
Screenshots (left hand side is after fixing)

image

### CODE REVIEW

**Comment by Radha-Alberta** [comment]
- [ ] gap between secondary text and badge is less than compare to heading and secondary text.

image

**Comment by vanessatran-ddi** [comment]
> * [x]  gap between secondary text and badge is less than compare to heading and secondary text.
> 
> image

I updated. 
image

**Comment by Radha-Alberta** [comment]
- [ ] mobile the accordion with just a heading is too big

image

**Comment by Radha-Alberta** [comment]
- [ ] Margins/Padding Issue with secondary text and badges

**Current:**
image

**Figma:**
image

**Pull request closed without merging**
