### PR TITLE
feat(DDIDS-1152, DDIDS-1213): Table component number column styling

### PR DESCRIPTION
**Pull request by amar-ABgov**
### TIcket
https://goa-dio.atlassian.net/browse/DDIDS-1152
 https://goa-dio.atlassian.net/browse/DDIDS-1213

#### Changes
* Added a new package to support the use of `:global` with svelte custom components. [Details](https://github.com/sveltejs/svelte/issues/2969#issuecomment-894511663)
* - [x] ~~Will update the storybook docs once https://github.com/GovAlta/ui-components/pull/1025/ is merged~~

### CODE REVIEW

**Review by chrisolsen — DISMISSED** [review]

**Comment by Radha-Alberta** [comment]
The height of the row is increased after adding class "goa-table-number-column" to a td cell (Refer to the second row in the below example).
image

**Review by ArakTaiRoth — APPROVED** [review]

**Review by chrisolsen — APPROVED** [review]

**Pull request merged**
