### PR TITLE
2277 dynamic children

### PR DESCRIPTION
**Pull request by chrisolsen**
# Before (the change)

# After (the change)

## Make sure that you've checked the boxes below before you submit the PR

- [x] I have read and followed the [setup steps](https://goa-dio.atlassian.net/wiki/spaces/DS/pages/3086385489/Contribution+-+web+content#%5BinlineExtension%5DCode-contributions)
- [x] I have created necessary unit tests
- [x] I have tested the functionality in React.
- [ ]  I have tested the functionality in Angular.

## Steps needed to test

Angular
```
coming soon
```

React

```
  const [colors, setColors] = useState<string[]>([]);
  const [data, setData] = useState<string>("");
  const [tabData, setTabData] = useState<{heading: string, content: string}[]>([]);

  useEffect(() => {
    setTimeout(() => {
      setColors(["red", "blue", "green"]);
      setData("Hello")
      setTabData([
        {heading: "Tab 1", content: "Tab 1 content"},
        {heading: "Tab 2", content: "Tab 2 content"},
      ])
    }, 2000)
  }, []);

  function changeColors() {
    console.log("change colors")
    setColors(["yellow", "purple", "red"]);
  }

  function onChange(name: string, value: string | string[]) {
    // nothing  
  }
```

```
      <GoADropdown name="item" value="" onChange={onChange} native={true}>
        {colors.map(color =>
          <GoADropdownItem key={color} value={color} label={color}></GoADropdownItem>
        )}
      </GoADropdown>
      <GoADropdown name="item" value="" onChange={onChange}>
        {colors.map(color =>
          <GoADropdownItem key={color} value={color} label={color}></GoADropdownItem>
        )}
      </GoADropdown>
      <GoADropdown name="item" value="" onChange={onChange}>
        <GoADropdownItem key="red" value="red" label="Red"></GoADropdownItem>
        <GoADropdownItem key="blue" value="blue" label="blue"></GoADropdownItem>
        <GoADropdownItem key="green" value="green" label="green"></GoADropdownItem>
      </GoADropdown>

      <GoAButton onClick={changeColors}>Change Colors</GoAButton>

      <GoAContainer title="Delayed data">
        {data}
      </GoAContainer>
      <GoAContainer title="Static data">
        Static data
      </GoAContainer>


      <GoAAccordion heading={"Delayed data"}>
        {data}
      </GoAAccordion>
      <GoAAccordion heading={"Static data"}>
        Static data
      </GoAAccordion>

      <h3>Dynamic</h3>
      <GoATabs onChange={() => {}}>
        {tabData.map(tab => 
          <GoATab key={tab.heading} heading={tab.heading}>
            {tab.content}
          </GoATab>
        )}
      </GoATabs>

      <h3>Static</h3>
      <GoATabs onChange={() => {}}>
        <GoATab heading="Tab Item 1">
          Tab Item 1: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
        </GoATab>
        <GoATab heading="Tab Item 2">
          Tab Item 2: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
        </GoATab>
        <GoATab heading="Tab Item 3">
          Tab Item 3: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
        </GoATab>
      </GoATabs>

```

### CODE REVIEW

**Comment by lizhuomeng71** [comment]
for react,  
Width property does not take effect before dynamic children is added

Code Example

```
import React, { useState, useEffect } from 'react';
import { GoAIconButton, GoADropdown, GoADropdownItem, GoAButton, GoAContainer, GoAAccordion, GoATabs, GoATab } from "@abgov/react-components";

export default function Bug2277Page(props) {
  const [colors, setColors] = useState<string[]>([]);

  function addColors() {
    console.log("change colors")
    setColors(["yellow", "purple", "red"]);
  }


  return (
    <>
  
    <GoADropdown name="item" value="" onChange={onChange} width="650px">
      {colors.map(color =>
        <GoADropdownItem key={color} value={color} label={color}></GoADropdownItem>
      )}
    </GoADropdown>

    <GoAButton onClick={changeColors}>Change Colors</GoAButton>

    </>
  )
}
```

**Comment by lizhuomeng71** [comment]
For dynamic children, I am not sure if this is the correct behavior 

if a dropdown already have a child vs a dropdown previous does not have children. After dynamic children is added, the width is rendered differently 


This is the TS file
```

import { Component } from "@angular/core";
@Component({
  selector: "abgov-styles",
  templateUrl: "./bug2277Page.component.html",
})
export class Bug2277PageComponent {
  colors: string[] = [];
  data: string = '';
  tabData: { heading: string; content: string }[] = [];

  ngOnInit(): void {
    setTimeout(() => {
      this.data = 'Hello';
      this.tabData = [
        { heading: 'Tab 1', content: 'Tab 1 content' },
        { heading: 'Tab 2', content: 'Tab 2 content' },
      ];
    }, 2000);
  }

  changeColors(): void {
    console.log('change colors');
    this.colors = ['yellow', 'red, red, red, red, red, red, red, red, red, red, red, red, red', 'purple', 'black', 'red'];
  }

  addColors(): void {
    console.log('add colors');
    this.colors = ['yellow', 'red'];
  }

  onChange(event: any): void {
    // Handle dropdown change logic
    console.log('Dropdown change:', event);
  }
}
```

This is the Html file

NOTICE, THE FIRST DROPDOWN HAVE ONE CHILD BEFORE DYNAMIC CHILDREN IS ADDED
```
<div>

      <goa-dropdown [name]="'item'" [value]="''" (change)="onChange($event)">
        <goa-dropdown-item key="red" value="red" label="red, red, red, red"></goa-dropdown-item>
        <ng-container *ngFor="let color of colors">
          <goa-dropdown-item [value]="color" [label]="color" mountType="prepend"></goa-dropdown-item>
        </ng-container>
      </goa-dropdown>

      <br /><br /><br /><br /><br />


      <goa-dropdown [name]="'item'" [value]="''" (change)="onChange($event)">
        <ng-container *ngFor="let color of colors">
          <goa-dropdown-item [value]="color" [label]="color"></goa-dropdown-item>
        </ng-container>
      </goa-dropdown>

      <br /><br /><br /><br /><br />


      <goa-button (click)="changeColors()">Change Colors</goa-button>
      <goa-button (click)="addColors()">Add Colors</goa-button>
    </div>

```

This is the video

https://jam.dev/c/caacfe10-a874-4e78-bcb9-160cd3c53bb5

**Comment by ArakTaiRoth** [comment]
@chrisolsen Looks like there's an issue with Dropdowns still. I don't need `mountType` or `{" "}` blank space, so that part is fixed. But I still seem to need the random UUID key for each item. Here's a [jam.dev](https://jam.dev/c/9670a346-716a-45c6-afec-623c9be91c0e) showing the issue, and here's the code creating the issue:

```javascript
import {
  GoABlock,
  GoACallout,
  GoAButton,
  GoAButtonGroup,
  GoADropdown,
  GoADropdownItem,
  GoAFormItem,
} from "@abgov/react-components";
import { useState } from "react";

export function DropdownRoute() {
  const parents = ["One", "Two", "Three"];
  const childrenOne = ["Alpha", "Beta"];
  const childrenTwo = ["Alpha", "Beta", "Gamma"];
  const childrenThree = ["Alpha", "Gamma"];
  const [children, setChildren] = useState<string[]>([]);

  const loadChildren = (name: string, values: string[] | string) => {
    if (typeof values === "string") {
      // console.log("values", values);
      if (values === "One") setChildren(childrenOne);
      else if (values === "Two") setChildren(childrenTwo);
      else setChildren(childrenThree);
    }
  };

  const addChild = (newChild: string, where: "prepend" | "append") => {
    if (where === "append") setChildren([...children, newChild]);
    else setChildren([newChild, ...children]);
  };

  return (
    <main>
      <GoABlock direction="column">
        <GoAFormItem label="Parent" requirement="optional">
          <GoADropdown name="parent" placeholder="Select a value" onChange={loadChildren}>
            {parents.map((parent) => (
              <GoADropdownItem key={parent} value={parent} label={parent} />
            ))}
          </GoADropdown>
        </GoAFormItem>
        <GoAButtonGroup alignment="start">
          <GoAButton onClick={() => loadChildren("", "One")}>
            Load children for One
          </GoAButton>
          <GoAButton onClick={() => loadChildren("", "Two")}>
            Load children for Two
          </GoAButton>
          <GoAButton onClick={() => loadChildren("", "Three")}>
            Load children for Three
          </GoAButton>
        </GoAButtonGroup>
        <GoAButtonGroup alignment="start">
          <GoAButton onClick={() => addChild("new Child", "prepend")}>
            Add child at the beginning
          </GoAButton>
          <GoAButton onClick={() => addChild("new Child", "append")}>
            Add child at the end
          </GoAButton>
        </GoAButtonGroup>
        <GoAFormItem label="Children" requirement="optional">
          <GoADropdown
            name="children"
            placeholder="Select a value"
            width="20ch"
            onChange={function (name: string, values: string[] | string): void {
              throw new Error("Function not implemented.");
            }}
          >
            {children.map((child, index) => (
              <GoADropdownItem
                key={child}
                // key={crypto.randomUUID()}
                value={child}
                label={child}
              />
            ))}
          </GoADropdown>
          <select name="children">
            {children.map((child) => (
              <option key={child} value={child}>
                {child}
              </option>
            ))}
          </select>
          <ul>
            {children.map((child) => (
              <li key={child}>{child}</li>
            ))}
          </ul>
        </GoAFormItem>
        <GoABlock direction="row">
          {children.map((child, index) => (
            <GoACallout key={child} type="information">
              {child}
            </GoACallout>
          ))}
        </GoABlock>
      </GoABlock>
    </main>
  );
}
```
If I uncomment the other `key` line, and comment out the `key={child}` line, everything works as expected.

**Review by syedszeeshan — APPROVED** [review]

**Review by ArakTaiRoth — APPROVED** [review]

**Pull request merged**
