### PR TITLE
fix(#1952): prevent cypress errors when running tests in browser

### PR DESCRIPTION
**Pull request by chrisolsen**

### CODE REVIEW

**Comment by lizhuomeng71** [comment]
I still express the same issue with this pull request

image

**Comment by lizhuomeng71** [comment]
my cypress version

Cypress package version: 13.13.0
Cypress binary version: 13.13.0
Electron version: 27.3.10
Bundled Node version:
18.17.1

**Comment by lizhuomeng71** [comment]
issue is actually resolved in alpha for both react and angular

**Comment by lizhuomeng71** [comment]
Screenshot 2024-07-17 112445

**Review by syedszeeshan — APPROVED** [review]

**Comment by ArakTaiRoth** [comment]
Closing this PR as it's no longer necessary, the issue was fixed in another PR

**Pull request closed without merging**
