### PR TITLE
fix(#2002): Add color support for pencil icon

### PR DESCRIPTION
**Pull request by ArakTaiRoth**
# Testing Code

Angular:
```html
<goa-icon type="pencil" size="medium" fillcolor="green" theme="filled" />
<goa-icon-button variant="destructive" size="medium" icon="pencil" arialabel="Pencil icon"></goa-icon-button>
```

React:
```javascript
return (
  <>
    <GoAIcon type="pencil" size="medium" fillColor="green" theme="filled" />
    <GoAIconButton variant="destructive" size="medium" icon="pencil" />
  </>
);
```

# Before (the change)

image

# After (the change)

image

## Make sure that you've checked the boxes below before you submit the PR

- [x] I have read and followed the [setup steps](https://goa-dio.atlassian.net/wiki/spaces/DS/pages/3086385489/Contribution+-+web+content#%5BinlineExtension%5DCode-contributions)
- [x] I have created necessary unit tests
- [x] I have tested the functionality in both React and Angular.

## Steps needed to test

Use the code listed above to test

### CODE REVIEW

**Comment by lizhuomeng71** [comment]
Pencil icon also missing the affect for size (small medium large)

**Comment by lizhuomeng71** [comment]
image

**Comment by ArakTaiRoth** [comment]
@lizhuomeng71 That work is not included in this story, I've made a new story detailing that for all custom icons, https://github.com/GovAlta/ui-components/issues/2038

**Review by chrisolsen — APPROVED** [review]

**Comment by lizhuomeng71** [comment]
This issue is verified, color support is implement, size change is implement in another  ticket

**Pull request merged**
