### PR TITLE
Fix(#1443): Date-picker value binding

### PR DESCRIPTION
**Pull request by hassananv**

### CODE REVIEW

**Comment by Radha-Alberta** [comment]
**Steps to reproduce:**
1. open date picker
2. select date "March 4th 2022"

**Expected Result:** March 4th 2022 should be displayed in date picker input
**Current Result**: March 3rd 2022 is visible in date picker input


**Steps to Reproduce:**
1. open date picker
2. select value Feb 27 2022
3. click on Reset Button
**Expected**: date picker value should change
**Current**: Unable to change the date picker value

**Comment by Radha-Alberta** [comment]
- React, reset button works only once.
- Angular Works Fine

**React:**
**Steps to Reproduce:**
1. Open date picker
2. select date '15th April 2022'
3. click on reset button [ Reset button works as expected, date will reset to March 24th 2022 ]
4. select date '14th April 2022'
4. click on reset button

**Expected Result:**  Date should reset to March 24th 2022
**Current Result:** Date will not change to March 24th 2022

**Code:**
  ```
const [dateValue, setDateValue] = useState<Date | undefined>(new Date("2022-03-2"));

  function resetValue() {
    console.log("Clicked");
    setDateValue(new Date("2023-03-25"));
  }
  <GoADatePicker onChange={(name: string, value: Date) => { }} value={dateValue} />
      <GoAButton onClick={resetValue}>
        Reset Value
      </GoAButton>
```

**Comment by hassananv** [comment]
> * React, reset button works only once.
> * Angular Works Fine
> 
> **React:** **Steps to Reproduce:**
> 
> 1. Open date picker
> 2. select date '15th April 2022'
> 3. click on reset button [ Reset button works as expected, date will reset to March 24th 2022 ]
> 4. select date '14th April 2022'
> 5. click on reset button
> 
> **Expected Result:** Date should reset to March 24th 2022 **Current Result:** Date will not change to March 24th 2022
> 
> **Code:**
> 
> ```
> const [dateValue, setDateValue] = useState<Date | undefined>(new Date("2022-03-2"));
> 
> function resetValue() {
>   console.log("Clicked");
>   setDateValue(new Date("2023-03-25"));
> }
> <GoADatePicker onChange={(name: string, value: Date) => { }} value={dateValue} />
>     <GoAButton onClick={resetValue}>
>       Reset Value
>     </GoAButton>
> ```

@Radha-Alberta 
Please check like this:

> **Code:**
> 
> ```
> const [dateValue, setDateValue] = useState<Date | undefined>(new Date(2022,3,2));
> 
> function resetValue() {
>   console.log("Clicked");
>   setDateValue(new Date(2023,3,25));
> }
><GoADatePicker  onChange={(name: string, value: Date) => { setDateValue(value) }} value={dateValue}  /> 
>     <GoAButton onClick={resetValue}>
>       Reset Value
>     </GoAButton>
> ```

**Review by ArakTaiRoth — DISMISSED** [review]

**Review by chrisolsen — APPROVED** [review]

**Comment by chrisolsen** [comment]
@hassananv Thanks for the patch! Before this is merged can you squash your changes and force push back to your repo?

**Review by chrisolsen — CHANGES_REQUESTED** [review]
Need to squash commits

**Review by chrisolsen — CHANGES_REQUESTED** [review]
Sorry Hassan, one more thing. To get the fix properly recognized by the semantic-release lib you will have to downcase the `Fix(#1443):...` to `fix(#1443):...` in your commit message (it doesn't matter for the Github PR title).

**Pull request merged**
