### PR TITLE
fix(#1818): Adding multiple back to File Upload

### PR DESCRIPTION
**Pull request by ArakTaiRoth**
# Testing

Create a Drag and Drop variant of the File Upload. Make sure you can select multiple files using it, while using the file select window (not dragging and dropping).

### CODE REVIEW

**Comment by lizhuomeng71** [comment]
issue is verified on angular and react for chrome, and firefox,

There is 2 issues identified related to accept properties, since it's not related to this PR, I created new ticket for it

image

**Review by chrisolsen — APPROVED** [review]

**Pull request merged**
