### PR TITLE
chore(#1346): Update modal Storybook and react component

### PR DESCRIPTION
**Pull request by ArakTaiRoth**

### CODE REVIEW

**Comment by Radha-Alberta** [comment]
- Callout variant is having both 'x' icon and action button, should only contain action buttons as per figma design

image

**Figma:**
image
image

**Comment by Radha-Alberta** [comment]
> * [ ]  Callout variant is having both 'x' icon and action button, should only contain action buttons as per figma design
> 
> image
> 
> **Figma:** image image

We will create a new ticket to track this issue

**Review by chrisolsen — APPROVED** [review]

**Pull request merged**
